[kafka]
host = "localhost"
port = 9092


[model.facial_processing.detector]
model_path = "/home/stepan/rust/projects/recognition_all/ml_rust/models/antelopev2/detection/model.onnx"
model_name = "detector"


[model.facial_processing.recognizer]
model_path = "/home/stepan/rust/projects/recognition_all/ml_rust/models/antelopev2/recognition/model.onnx"
model_name = "recognizer"


[model.search.textual]
model_path = "/home/stepan/rust/projects/recognition_all/ml_rust/models/clip/text/model.onnx"
model_name = "sentence-transformers/clip-ViT-B-32-multilingual-v1"


[model.search.visual]
model_path = "/home/stepan/rust/projects/recognition_all/ml_rust/models/clip/image/model.onnx"
model_name = "visual"
