version: "2"
services:
  zookeeper-local:
    image: docker.io/confluentinc/cp-zookeeper:latest
    container_name: zookeeper-local
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:22181

  kafka-local:
    image: docker.io/confluentinc/cp-kafka:latest
    container_name: kafka-local
    restart: always
    depends_on:
      - zookeeper-local
    ports:
      - 9092:29092
      - 29092:29092
    environment:
      KAFKA_TOPIC_MAX_MESSAGE_BYTES: 20971520
      KAFKA_REPLICA_FETCH_MAX_BYTES: 20971520
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-local:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-local:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui-local:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-local:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper-local:22181
    links:
      - kafka-local
      - zookeeper-local
