[package]
name = "bin"
version = "0.1.0"
edition = "2021"

[dependencies]
pipeline = { path = "../pipeline" }
rdkafka = { version = "0.25", features = ["cmake-build"] }
uuid = "1.11.0"
tokio = { version = "1.28.2", features = ["full"] }
serde_json = "1.0.117"
